<?php

/**
 * @file
 * Custom hooks and functions for module.
 */

use Drupal\myevents\Event\MyeventsPreprocessEvent;

/**
 * Implements hook_preprocess_HOOK().
 */
function myevents_preprocess_html(&$variables) {
  /** @var \Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher $dispatcher */
  $dispatcher = \Drupal::service('event_dispatcher');
  // Create event object passing arguments.
  $event = new MyeventsPreprocessEvent($variables);
  // Call it.
  $dispatcher->dispatch(MyeventsPreprocessEvent::PREPROCESS_HTML, $event);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function myevents_preprocess_page(&$variables) {
  /** @var \Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher $dispatcher */
  $dispatcher = \Drupal::service('event_dispatcher');
  // Create event object passing arguments.
  $event = new MyeventsPreprocessEvent($variables);
  // Call it.
  $dispatcher->dispatch(MyeventsPreprocessEvent::PREPROCESS_PAGE, $event);
}
